prefix: default
device: cuda
mode: train
log_dir: logs/${mode}
eval_data_path: null
use_wandb: true
seed: 0

agent:
  agent_name: dp

env:
  env_class: ???
  num_eef: 2
  dof: 7
  eef_dim: 13
  vectorize: false
  args:
    num_eef: ${env.num_eef}
    dof: ${env.dof}
    seed: ${seed}
    obs_mode: "pc"
    ac_mode: "rel"
    max_episode_length: ???
    num_points: ${data.dataset.num_points}
    randomize_rotation: false
    randomize_scale: false
    scale_low: 1.0
    scale_high: 1.0
    scale_aspect_limit: 100.0
    uniform_scaling: false

data:
  dataset_class: base_dataset
  dataset:
    num_training_steps: ???
    path: null
    num_points: 1024
    num_augment: 0
    same_aug_per_sample: true
    aug_keep_original: true
    aug_scale_low: 0.5
    aug_scale_high: 1.5
    aug_scale_aspect_limit: 1.0
    aug_scale_rot: -1
    aug_scale_pos: 0.1
    aug_zero_z_offset: false
    aug_center: [0., 0., 0.]
    shuffle_pc: true
    num_workers: 12
    dof: ${env.dof}
    num_eef: ${env.num_eef}
    eef_dim: ${env.eef_dim}
    obs_horizon: ${model.obs_horizon}
    pred_horizon: ${model.pred_horizon}
    reduce_horizon_dim: false
    min_demo_length: 15

model:
  hidden_dim: 32
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_schedule: squaredcos_cap_v2
    clip_sample: true
    prediction_type: epsilon
  obs_horizon: 2
  ac_horizon: 8
  pred_horizon: 16
  encoder:
    c_dim: ${model.hidden_dim}
    backbone_type: vn_pointnet
    backbone_args:
      h_dim: ${model.hidden_dim}
      c_dim: ${model.encoder.c_dim}
      num_layers: 4
      knn: 8
  obs_mode: ${env.args.obs_mode}
  ac_mode: ${env.args.ac_mode}
  use_torch_compile: false

training:
  batch_size: 32
  num_epochs: 2000
  lr: 3e-5
  weight_decay: 1e-6
  num_eval_episodes: 10
  eval_interval: 1000000 # do not eval during training
  save_interval: 50
  vis_interval: 100
  ckpt: null

eval:
  last_ckpt: 1999
  num_ckpts_to_eval: 5

hydra:
  run:
    dir: ${log_dir}/${prefix}

wandb:
  entity: [enter wandb entity name here]
  project: [enter wandb project name here]
